"""empty message

Revision ID: 648c921856f6
Revises: 
Create Date: 2021-03-21 15:56:36.015922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648c921856f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('rooms', sa.String(length=3), nullable=True),
    sa.Column('bathrooms', sa.String(length=3), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('ptype', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=4096), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
